import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import toast from "react-hot-toast";
import { getAllOrders } from "../services/ordersApi.js";
import { generateInvoice, getInvoices } from "../services/invoicesApi.js";
import { useAuth } from "../hooks/useAuth.js";

const INVOICES_PER_PAGE = 10;

const InvoicesManagement = () => {
  const { user } = useAuth();
  const basePath = user?.role === "ADMIN" ? "/admin" : "/manager";
  const [invoices, setInvoices] = useState([]);
  const [orders, setOrders] = useState([]);
  const [selectedOrderId, setSelectedOrderId] = useState("");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [currentPage, setCurrentPage] = useState(1);

  const fetchData = async () => {
    setLoading(true);
    try {
      const [invoicesData, ordersData] = await Promise.all([getInvoices(), getAllOrders()]);
      setInvoices(invoicesData.invoices || []);
      setOrders((ordersData.orders || []).filter((order) => order.orderStatus === "APPROVED"));
    } catch (err) {
      toast.error(err.message || "Failed to load invoices");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

  const uninvoicedOrders = useMemo(() => {
    const invoiceOrderIds = new Set(invoices.map((invoice) => String(invoice.order?._id || invoice.order)));
    return orders.filter((order) => !invoiceOrderIds.has(String(order._id)));
  }, [invoices, orders]);

  useEffect(() => {
    setCurrentPage(1);
  }, [invoices]);

  const totalPages = Math.max(1, Math.ceil(invoices.length / INVOICES_PER_PAGE));
  const paginatedInvoices = useMemo(() => {
    const startIndex = (currentPage - 1) * INVOICES_PER_PAGE;
    return invoices.slice(startIndex, startIndex + INVOICES_PER_PAGE);
  }, [currentPage, invoices]);
  const pageStart = invoices.length === 0 ? 0 : (currentPage - 1) * INVOICES_PER_PAGE + 1;
  const pageEnd = Math.min(currentPage * INVOICES_PER_PAGE, invoices.length);

  const handleGenerateInvoice = async () => {
    if (!selectedOrderId) {
      toast.error("Select an order first");
      return;
    }

    setSaving(true);
    try {
      await generateInvoice({ orderId: selectedOrderId });
      toast.success("Invoice generated successfully");
      setSelectedOrderId("");
      fetchData();
    } catch (err) {
      toast.error(err.message || "Failed to generate invoice");
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return <div className="py-20 text-center text-stone-500">Loading invoices...</div>;
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-stone-900">Invoices</h1>
        <p className="mt-1 text-stone-500">
          Generate invoice records for approved orders and open printable invoice pages.
        </p>
      </div>

      <div className="rounded-xl border border-stone-200 bg-white p-5">
        <h2 className="text-lg font-semibold text-stone-900">Generate Invoice</h2>
        <div className="mt-4 flex flex-col gap-3 md:flex-row">
          <select
            value={selectedOrderId}
            onChange={(e) => setSelectedOrderId(e.target.value)}
            className="flex-1 rounded-lg border border-stone-300 bg-white px-3 py-2 text-sm"
          >
            <option value="">Select approved order</option>
            {uninvoicedOrders.map((order) => (
              <option key={order._id} value={order._id}>
                {order.contractor?.name} - Rs. {Number(order.totalAmount).toFixed(2)}
              </option>
            ))}
          </select>
          <button
            type="button"
            disabled={saving}
            onClick={handleGenerateInvoice}
            className="rounded-lg bg-teal-600 px-4 py-2 text-sm font-medium text-white hover:bg-teal-700 disabled:opacity-50"
          >
            {saving ? "Generating..." : "Generate Invoice"}
          </button>
        </div>
      </div>

      <div className="overflow-hidden rounded-xl border border-stone-200 bg-white">
        <div className="overflow-x-auto">
          <table className="w-full min-w-[900px]">
            <thead className="bg-stone-50">
              <tr className="border-b border-stone-200">
                <th className="px-5 py-3 text-left text-xs font-medium uppercase tracking-wide text-stone-500">Invoice No</th>
                <th className="px-5 py-3 text-left text-xs font-medium uppercase tracking-wide text-stone-500">Contractor</th>
                <th className="px-5 py-3 text-left text-xs font-medium uppercase tracking-wide text-stone-500">Amount</th>
                <th className="px-5 py-3 text-left text-xs font-medium uppercase tracking-wide text-stone-500">Generated By</th>
                <th className="px-5 py-3 text-left text-xs font-medium uppercase tracking-wide text-stone-500">Generated At</th>
                <th className="px-5 py-3 text-right text-xs font-medium uppercase tracking-wide text-stone-500">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-stone-100">
              {paginatedInvoices.map((invoice) => (
                <tr key={invoice._id}>
                  <td className="px-5 py-4 font-medium text-stone-900">{invoice.invoiceNumber}</td>
                  <td className="px-5 py-4">
                    <p className="font-medium text-stone-900">{invoice.contractor?.name}</p>
                    <p className="text-sm text-stone-500">{invoice.contractor?.email}</p>
                  </td>
                  <td className="px-5 py-4 text-sm text-stone-700">Rs. {Number(invoice.totalAmount).toFixed(2)}</td>
                  <td className="px-5 py-4 text-sm text-stone-700">{invoice.generatedBy?.name || "-"}</td>
                  <td className="px-5 py-4 text-sm text-stone-600">{new Date(invoice.generatedAt).toLocaleString()}</td>
                  <td className="px-5 py-4 text-right">
                    <Link
                      to={`${basePath}/invoices/${invoice._id}`}
                      className="rounded-lg border border-stone-300 px-3 py-2 text-sm font-medium text-stone-700 hover:bg-stone-50"
                    >
                      View Invoice
                    </Link>
                  </td>
                </tr>
              ))}
              {invoices.length === 0 && (
                <tr>
                  <td colSpan="6" className="px-5 py-12 text-center text-stone-500">
                    No invoices generated yet.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
        {invoices.length > 0 && (
          <div className="flex flex-col gap-3 border-t border-stone-200 px-5 py-4 sm:flex-row sm:items-center sm:justify-between">
            <p className="text-sm text-stone-500">
              Showing {pageStart}-{pageEnd} of {invoices.length} invoices
            </p>
            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={() => setCurrentPage((page) => Math.max(page - 1, 1))}
                disabled={currentPage === 1}
                className="rounded-lg border border-stone-300 px-3 py-2 text-sm font-medium text-stone-700 hover:bg-stone-50 disabled:cursor-not-allowed disabled:opacity-50"
              >
                Previous
              </button>
              <span className="rounded-lg bg-stone-100 px-3 py-2 text-sm font-medium text-stone-700">
                Page {currentPage} of {totalPages}
              </span>
              <button
                type="button"
                onClick={() => setCurrentPage((page) => Math.min(page + 1, totalPages))}
                disabled={currentPage === totalPages}
                className="rounded-lg border border-stone-300 px-3 py-2 text-sm font-medium text-stone-700 hover:bg-stone-50 disabled:cursor-not-allowed disabled:opacity-50"
              >
                Next
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default InvoicesManagement;
